### ISSUE TITLE
Create online commands for deploying/undeploying

### ISSUE THREAD

**Issue by rhatlapa** [wildfly-extras/creaper#42] opened 2015-12-17 15:40 UTC
There should be created command, which will allow to easily create deployment operation, which can be used for both: server in standalone and in domain mode.

**Comment by rhatlapa** [comment] 2016-02-01 16:33
I would like to discuss how to create undeploy command for domain (its behaviour)

There is mainly one concern and that is deployment in repository vs being deployed to some specific server groups.

The deployment can't be removed from deployment repository till it is used by some server group.

Here is the problematic part, which is to decide whether it should be only undeployed/removed from specified server group or also from the deployment repository.

**Comment by rhatlapa** [comment] 2016-02-01 16:40
The easiest way seems to me making builder over CLI operation `undeploy` in this case. Where it would allow to specify whether it should be undeployed from all relevant server groups or just from specific ones.

**Comment by Ladicek** [comment] 2016-02-02 07:02
The undeploy command can have options specific to managed domain that would specify the intended behavior.

The key here is the default behavior where no such options are provided -- should it undeploy from all server groups and remove from content repository? Seems quite brutal, but probably closest to the standalone case. Or any other options?

**Comment by Ladicek** [comment] 2016-02-17 13:16
Fixed by #57.

**Closed by Ladicek** 2016-02-17 13:16 UTC
